// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#ifndef __BINDINGS_MY_WORLD_H
#define __BINDINGS_MY_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stdbool.h>

typedef struct {
  uint8_t*ptr;
  size_t len;
} my_world_string_t;

typedef struct {
  uint8_t tag;
  union {
    uint16_t other;
  } val;
} levo_portal_my_imports_mouse_button_t;

#define LEVO_PORTAL_MY_IMPORTS_MOUSE_BUTTON_LEFT 0
#define LEVO_PORTAL_MY_IMPORTS_MOUSE_BUTTON_RIGHT 1
#define LEVO_PORTAL_MY_IMPORTS_MOUSE_BUTTON_MIDDLE 2
#define LEVO_PORTAL_MY_IMPORTS_MOUSE_BUTTON_OTHER 3

typedef uint8_t levo_portal_my_imports_key_code_t;

#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY1 0
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY2 1
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY3 2
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY4 3
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY5 4
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY6 5
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY7 6
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY8 7
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY9 8
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KEY0 9
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_A 10
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_B 11
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_C 12
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_D 13
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_E 14
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F 15
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_G 16
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_H 17
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_I 18
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_J 19
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_K 20
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_L 21
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_M 22
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_N 23
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_O 24
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_P 25
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_Q 26
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_R 27
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_S 28
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_T 29
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_U 30
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_V 31
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_W 32
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_X 33
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_Y 34
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_Z 35
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ESCAPE 36
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F1 37
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F2 38
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F3 39
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F4 40
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F5 41
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F6 42
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F7 43
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F8 44
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F9 45
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F10 46
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F11 47
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F12 48
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F13 49
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F14 50
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F15 51
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F16 52
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F17 53
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F18 54
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F19 55
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F20 56
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F21 57
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F22 58
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F23 59
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_F24 60
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SNAPSHOT 61
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SCROLL 62
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PAUSE 63
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_INSERT 64
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_HOME 65
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_DELETE 66
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_END 67
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PAGE_DOWN 68
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PAGE_UP 69
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_LEFT 70
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_UP 71
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_RIGHT 72
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_DOWN 73
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_BACK 74
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_RETURN 75
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SPACE 76
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_COMPOSE 77
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CARET 78
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMLOCK 79
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD0 80
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD1 81
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD2 82
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD3 83
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD4 84
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD5 85
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD6 86
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD7 87
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD8 88
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD9 89
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ABNT_C1 90
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ABNT_C2 91
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_ADD 92
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_APOSTROPHE 93
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_APPS 94
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ASTERISK 95
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PLUS 96
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_AT 97
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_AX 98
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_BACKSLASH 99
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CALCULATOR 100
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CAPITAL 101
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_COLON 102
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_COMMA 103
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CONVERT 104
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_DECIMAL 105
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_DIVIDE 106
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_EQUALS 107
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_GRAVE 108
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KANA 109
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_KANJI 110
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ALT_LEFT 111
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_BRACKET_LEFT 112
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CONTROL_LEFT 113
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SHIFT_LEFT 114
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SUPER_LEFT 115
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MAIL 116
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MEDIA_SELECT 117
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MEDIA_STOP 118
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MINUS 119
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_MULTIPLY 120
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MUTE 121
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_MY_COMPUTER 122
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NAVIGATE_FORWARD 123
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NAVIGATE_BACKWARD 124
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NEXT_TRACK 125
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NO_CONVERT 126
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_COMMA 127
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_ENTER 128
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_EQUALS 129
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_OEM102 130
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PERIOD 131
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PLAY_PAUSE 132
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_POWER 133
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PREV_TRACK 134
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_ALT_RIGHT 135
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_BRACKET_RIGHT 136
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CONTROL_RIGHT 137
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SHIFT_RIGHT 138
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SUPER_RIGHT 139
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SEMICOLON 140
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SLASH 141
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SLEEP 142
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_STOP 143
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_NUMPAD_SUBTRACT 144
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_SYSRQ 145
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_TAB 146
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_UNDERLINE 147
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_UNLABELED 148
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_VOLUME_DOWN 149
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_VOLUME_UP 150
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WAKE 151
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_BACK 152
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_FAVORITES 153
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_FORWARD 154
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_HOME 155
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_REFRESH 156
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_SEARCH 157
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_WEB_STOP 158
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_YEN 159
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_COPY 160
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_PASTE 161
#define LEVO_PORTAL_MY_IMPORTS_KEY_CODE_CUT 162

typedef struct {
  float x;
  float y;
} levo_portal_my_imports_position_t;

typedef struct {
  float width;
  float height;
} levo_portal_my_imports_size_t;

typedef struct {
  bool is_some;
  levo_portal_my_imports_position_t val;
} levo_portal_my_imports_option_position_t;

// Imported Functions from `levo:portal/my-imports`
extern void levo_portal_my_imports_print(my_world_string_t *msg);
extern void levo_portal_my_imports_fill_style(my_world_string_t *color);
extern void levo_portal_my_imports_fill_rect(float x, float y, float width, float height);
extern void levo_portal_my_imports_begin_path(void);
extern void levo_portal_my_imports_move_to(float x, float y);
extern void levo_portal_my_imports_cubic_bezier_to(float x1, float y1, float x2, float y2, float x3, float y3);
extern void levo_portal_my_imports_arc(float x, float y, float radius, float sweep_angle, float x_rotation);
extern void levo_portal_my_imports_close_path(void);
extern void levo_portal_my_imports_fill(void);
extern void levo_portal_my_imports_label(my_world_string_t *text, float x, float y, float size, my_world_string_t *color);
extern void levo_portal_my_imports_link(my_world_string_t *url, my_world_string_t *text, float x, float y, float size);
extern float levo_portal_my_imports_delta_seconds(void);
extern bool levo_portal_my_imports_key_just_pressed(levo_portal_my_imports_key_code_t key);
extern bool levo_portal_my_imports_key_pressed(levo_portal_my_imports_key_code_t key);
extern bool levo_portal_my_imports_key_just_released(levo_portal_my_imports_key_code_t key);
extern bool levo_portal_my_imports_mouse_button_just_pressed(levo_portal_my_imports_mouse_button_t *btn);
extern bool levo_portal_my_imports_mouse_button_just_released(levo_portal_my_imports_mouse_button_t *btn);
extern bool levo_portal_my_imports_mouse_button_pressed(levo_portal_my_imports_mouse_button_t *btn);
extern bool levo_portal_my_imports_cursor_position(levo_portal_my_imports_position_t *ret);
extern void levo_portal_my_imports_canvas_size(levo_portal_my_imports_size_t *ret);

// Exported Functions from `my-world`
void my_world_update(void);
void my_world_setup(void);

// Helper Functions

void levo_portal_my_imports_mouse_button_free(levo_portal_my_imports_mouse_button_t *ptr);

void levo_portal_my_imports_option_position_free(levo_portal_my_imports_option_position_t *ptr);

// Transfers ownership of `s` into the string `ret`
void my_world_string_set(my_world_string_t *ret, char*s);

// Creates a copy of the input nul-terminate string `s` and
// stores it into the component model string `ret`.
void my_world_string_dup(my_world_string_t *ret, const char*s);

// Deallocates the string pointed to by `ret`, deallocating
// the memory behind the string.
void my_world_string_free(my_world_string_t *ret);

#ifdef __cplusplus
}
#endif
#endif
