// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#include "my_world.h"


__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("print")))
extern void __wasm_import_levo_portal_my_imports_print(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill-style")))
extern void __wasm_import_levo_portal_my_imports_fill_style(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill-rect")))
extern void __wasm_import_levo_portal_my_imports_fill_rect(float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("begin-path")))
extern void __wasm_import_levo_portal_my_imports_begin_path(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("move-to")))
extern void __wasm_import_levo_portal_my_imports_move_to(float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("cubic-bezier-to")))
extern void __wasm_import_levo_portal_my_imports_cubic_bezier_to(float, float, float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("arc")))
extern void __wasm_import_levo_portal_my_imports_arc(float, float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("close-path")))
extern void __wasm_import_levo_portal_my_imports_close_path(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill")))
extern void __wasm_import_levo_portal_my_imports_fill(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("label")))
extern void __wasm_import_levo_portal_my_imports_label(int32_t, int32_t, float, float, float, int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("link")))
extern void __wasm_import_levo_portal_my_imports_link(int32_t, int32_t, int32_t, int32_t, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("delta-seconds")))
extern float __wasm_import_levo_portal_my_imports_delta_seconds(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("key-just-pressed")))
extern int32_t __wasm_import_levo_portal_my_imports_key_just_pressed(int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("key-pressed")))
extern int32_t __wasm_import_levo_portal_my_imports_key_pressed(int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("key-just-released")))
extern int32_t __wasm_import_levo_portal_my_imports_key_just_released(int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("mouse-button-just-pressed")))
extern int32_t __wasm_import_levo_portal_my_imports_mouse_button_just_pressed(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("mouse-button-just-released")))
extern int32_t __wasm_import_levo_portal_my_imports_mouse_button_just_released(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("mouse-button-pressed")))
extern int32_t __wasm_import_levo_portal_my_imports_mouse_button_pressed(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("cursor-position")))
extern void __wasm_import_levo_portal_my_imports_cursor_position(int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("canvas-size")))
extern void __wasm_import_levo_portal_my_imports_canvas_size(int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("read-file")))
extern void __wasm_import_levo_portal_my_imports_read_file(int32_t, int32_t, int32_t);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void levo_portal_my_imports_mouse_button_free(levo_portal_my_imports_mouse_button_t *ptr) {
  switch ((int32_t) ptr->tag) {
    case 3: {
      break;
    }
  }
}

void levo_portal_my_imports_option_position_free(levo_portal_my_imports_option_position_t *ptr) {
  if (ptr->is_some) {
  }
}

void my_world_list_u8_free(my_world_list_u8_t *ptr) {
  for (size_t i = 0; i < ptr->len; i++) {
  }
  if (ptr->len > 0) {
    free(ptr->ptr);
  }
}

void levo_portal_my_imports_result_list_u8_void_free(levo_portal_my_imports_result_list_u8_void_t *ptr) {
  if (!ptr->is_err) {
    my_world_list_u8_free(&ptr->val.ok);
  }
}

void my_world_string_set(my_world_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void my_world_string_dup(my_world_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void my_world_string_free(my_world_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void levo_portal_my_imports_print(my_world_string_t *msg) {
  __wasm_import_levo_portal_my_imports_print((int32_t) (*msg).ptr, (int32_t) (*msg).len);
}

void levo_portal_my_imports_fill_style(my_world_string_t *color) {
  __wasm_import_levo_portal_my_imports_fill_style((int32_t) (*color).ptr, (int32_t) (*color).len);
}

void levo_portal_my_imports_fill_rect(float x, float y, float width, float height) {
  __wasm_import_levo_portal_my_imports_fill_rect(x, y, width, height);
}

void levo_portal_my_imports_begin_path(void) {
  __wasm_import_levo_portal_my_imports_begin_path();
}

void levo_portal_my_imports_move_to(float x, float y) {
  __wasm_import_levo_portal_my_imports_move_to(x, y);
}

void levo_portal_my_imports_cubic_bezier_to(float x1, float y1, float x2, float y2, float x3, float y3) {
  __wasm_import_levo_portal_my_imports_cubic_bezier_to(x1, y1, x2, y2, x3, y3);
}

void levo_portal_my_imports_arc(float x, float y, float radius, float sweep_angle, float x_rotation) {
  __wasm_import_levo_portal_my_imports_arc(x, y, radius, sweep_angle, x_rotation);
}

void levo_portal_my_imports_close_path(void) {
  __wasm_import_levo_portal_my_imports_close_path();
}

void levo_portal_my_imports_fill(void) {
  __wasm_import_levo_portal_my_imports_fill();
}

void levo_portal_my_imports_label(my_world_string_t *text, float x, float y, float size, my_world_string_t *color) {
  __wasm_import_levo_portal_my_imports_label((int32_t) (*text).ptr, (int32_t) (*text).len, x, y, size, (int32_t) (*color).ptr, (int32_t) (*color).len);
}

void levo_portal_my_imports_link(my_world_string_t *url, my_world_string_t *text, float x, float y, float size) {
  __wasm_import_levo_portal_my_imports_link((int32_t) (*url).ptr, (int32_t) (*url).len, (int32_t) (*text).ptr, (int32_t) (*text).len, x, y, size);
}

float levo_portal_my_imports_delta_seconds(void) {
  float ret = __wasm_import_levo_portal_my_imports_delta_seconds();
  return ret;
}

bool levo_portal_my_imports_key_just_pressed(levo_portal_my_imports_key_code_t key) {
  int32_t ret = __wasm_import_levo_portal_my_imports_key_just_pressed((int32_t) key);
  return ret;
}

bool levo_portal_my_imports_key_pressed(levo_portal_my_imports_key_code_t key) {
  int32_t ret = __wasm_import_levo_portal_my_imports_key_pressed((int32_t) key);
  return ret;
}

bool levo_portal_my_imports_key_just_released(levo_portal_my_imports_key_code_t key) {
  int32_t ret = __wasm_import_levo_portal_my_imports_key_just_released((int32_t) key);
  return ret;
}

bool levo_portal_my_imports_mouse_button_just_pressed(levo_portal_my_imports_mouse_button_t *btn) {
  int32_t variant;
  int32_t variant3;
  switch ((int32_t) (*btn).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant3 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      const uint16_t *payload2 = &(*btn).val.other;
      variant = 3;
      variant3 = (int32_t) (*payload2);
      break;
    }
  }
  int32_t ret = __wasm_import_levo_portal_my_imports_mouse_button_just_pressed(variant, variant3);
  return ret;
}

bool levo_portal_my_imports_mouse_button_just_released(levo_portal_my_imports_mouse_button_t *btn) {
  int32_t variant;
  int32_t variant3;
  switch ((int32_t) (*btn).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant3 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      const uint16_t *payload2 = &(*btn).val.other;
      variant = 3;
      variant3 = (int32_t) (*payload2);
      break;
    }
  }
  int32_t ret = __wasm_import_levo_portal_my_imports_mouse_button_just_released(variant, variant3);
  return ret;
}

bool levo_portal_my_imports_mouse_button_pressed(levo_portal_my_imports_mouse_button_t *btn) {
  int32_t variant;
  int32_t variant3;
  switch ((int32_t) (*btn).tag) {
    case 0: {
      variant = 0;
      variant3 = 0;
      break;
    }
    case 1: {
      variant = 1;
      variant3 = 0;
      break;
    }
    case 2: {
      variant = 2;
      variant3 = 0;
      break;
    }
    case 3: {
      const uint16_t *payload2 = &(*btn).val.other;
      variant = 3;
      variant3 = (int32_t) (*payload2);
      break;
    }
  }
  int32_t ret = __wasm_import_levo_portal_my_imports_mouse_button_pressed(variant, variant3);
  return ret;
}

void levo_portal_my_imports_cursor_position(levo_portal_my_imports_option_position_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_levo_portal_my_imports_cursor_position(ptr);
  levo_portal_my_imports_option_position_t option;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      option.is_some = false;
      break;
    }
    case 1: {
      option.is_some = true;
      option.val = (levo_portal_my_imports_position_t) {
        *((float*) (ptr + 4)),
        *((float*) (ptr + 8)),
      };
      break;
    }
  }
  *ret = option;
}

void levo_portal_my_imports_canvas_size(levo_portal_my_imports_size_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[8];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_levo_portal_my_imports_canvas_size(ptr);
  *ret = (levo_portal_my_imports_size_t) {
    *((float*) (ptr + 0)),
    *((float*) (ptr + 4)),
  };
}

void levo_portal_my_imports_read_file(my_world_string_t *path, levo_portal_my_imports_result_list_u8_void_t *ret) {
  __attribute__((__aligned__(4)))
  uint8_t ret_area[12];
  int32_t ptr = (int32_t) &ret_area;
  __wasm_import_levo_portal_my_imports_read_file((int32_t) (*path).ptr, (int32_t) (*path).len, ptr);
  levo_portal_my_imports_result_list_u8_void_t result;
  switch ((int32_t) (*((uint8_t*) (ptr + 0)))) {
    case 0: {
      result.is_err = false;
      result.val.ok = (my_world_list_u8_t) { (uint8_t*)(*((int32_t*) (ptr + 4))), (size_t)(*((int32_t*) (ptr + 8))) };
      break;
    }
    case 1: {
      result.is_err = true;
      break;
    }
  }
  *ret = result;
}

__attribute__((__export_name__("update")))
void __wasm_export_my_world_update(void) {
  my_world_update();
}

__attribute__((__export_name__("setup")))
void __wasm_export_my_world_setup(void) {
  my_world_setup();
}

extern void __component_type_object_force_link_my_world(void);
void __component_type_object_force_link_my_world_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_my_world();
}
