// Generated by `wit-bindgen` 0.16.0. DO NOT EDIT!
#include "host.h"


__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("print")))
extern void __wasm_import_levo_portal_my_imports_print(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill-style")))
extern void __wasm_import_levo_portal_my_imports_fill_style(int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill-rect")))
extern void __wasm_import_levo_portal_my_imports_fill_rect(float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("begin-path")))
extern void __wasm_import_levo_portal_my_imports_begin_path(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("move-to")))
extern void __wasm_import_levo_portal_my_imports_move_to(float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("cubic-bezier-to")))
extern void __wasm_import_levo_portal_my_imports_cubic_bezier_to(float, float, float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("arc")))
extern void __wasm_import_levo_portal_my_imports_arc(float, float, float, float, float);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("close-path")))
extern void __wasm_import_levo_portal_my_imports_close_path(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("fill")))
extern void __wasm_import_levo_portal_my_imports_fill(void);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("label")))
extern void __wasm_import_levo_portal_my_imports_label(int32_t, int32_t, float, float, float, int32_t, int32_t);

__attribute__((__import_module__("levo:portal/my-imports"), __import_name__("delta-seconds")))
extern float __wasm_import_levo_portal_my_imports_delta_seconds(void);

__attribute__((__weak__, __export_name__("cabi_realloc")))
void *cabi_realloc(void *ptr, size_t old_size, size_t align, size_t new_size) {
  (void) old_size;
  if (new_size == 0) return (void*) align;
  void *ret = realloc(ptr, new_size);
  if (!ret) abort();
  return ret;
}

// Helper Functions

void host_string_set(host_string_t *ret, char*s) {
  ret->ptr = (uint8_t*) s;
  ret->len = strlen(s);
}

void host_string_dup(host_string_t *ret, const char*s) {
  ret->len = strlen(s);
  ret->ptr = cabi_realloc(NULL, 0, 1, ret->len * 1);
  memcpy(ret->ptr, s, ret->len * 1);
}

void host_string_free(host_string_t *ret) {
  if (ret->len > 0) {
    free(ret->ptr);
  }
  ret->ptr = NULL;
  ret->len = 0;
}

// Component Adapters

void levo_portal_my_imports_print(host_string_t *msg) {
  __wasm_import_levo_portal_my_imports_print((int32_t) (*msg).ptr, (int32_t) (*msg).len);
}

void levo_portal_my_imports_fill_style(host_string_t *color) {
  __wasm_import_levo_portal_my_imports_fill_style((int32_t) (*color).ptr, (int32_t) (*color).len);
}

void levo_portal_my_imports_fill_rect(float x, float y, float width, float height) {
  __wasm_import_levo_portal_my_imports_fill_rect(x, y, width, height);
}

void levo_portal_my_imports_begin_path(void) {
  __wasm_import_levo_portal_my_imports_begin_path();
}

void levo_portal_my_imports_move_to(float x, float y) {
  __wasm_import_levo_portal_my_imports_move_to(x, y);
}

void levo_portal_my_imports_cubic_bezier_to(float x1, float y1, float x2, float y2, float x3, float y3) {
  __wasm_import_levo_portal_my_imports_cubic_bezier_to(x1, y1, x2, y2, x3, y3);
}

void levo_portal_my_imports_arc(float x, float y, float radius, float sweep_angle, float x_rotation) {
  __wasm_import_levo_portal_my_imports_arc(x, y, radius, sweep_angle, x_rotation);
}

void levo_portal_my_imports_close_path(void) {
  __wasm_import_levo_portal_my_imports_close_path();
}

void levo_portal_my_imports_fill(void) {
  __wasm_import_levo_portal_my_imports_fill();
}

void levo_portal_my_imports_label(host_string_t *text, float x, float y, float size, host_string_t *color) {
  __wasm_import_levo_portal_my_imports_label((int32_t) (*text).ptr, (int32_t) (*text).len, x, y, size, (int32_t) (*color).ptr, (int32_t) (*color).len);
}

float levo_portal_my_imports_delta_seconds(void) {
  float ret = __wasm_import_levo_portal_my_imports_delta_seconds();
  return ret;
}

__attribute__((__export_name__("update")))
void __wasm_export_host_update(void) {
  host_update();
}

__attribute__((__export_name__("setup")))
void __wasm_export_host_setup(void) {
  host_setup();
}

extern void __component_type_object_force_link_host(void);
void __component_type_object_force_link_host_public_use_in_this_compilation_unit(void) {
  __component_type_object_force_link_host();
}
