package levo:portal;

interface my-imports {
    gen-random-integer: func() -> u32;
    print-str: func(msg: string);
    print-u32: func(msg: u32);
}

world my-world {
  import my-imports;

  export update: func();

  export setup: func();
}