package levo:portal;

interface my-imports {
    gen-random-integer: func() -> u32;
    print: func(msg: string);
}

world my-world {
  import my-imports;

  export update: func();

  export setup: func();
}